live_config_reload = true

import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[window]
padding.x = 15
padding.y = 15
dimensions = { columns = 100, lines = 30}

opacity = 0.9
blur = true
decorations = 'None'


[shell]
program = "/bin/zsh"


[env]
TERM = "xterm-256color"

[font]
size = 17.0

# NotoSansM Nerd Font, JetBrains Mono Nerd Font, Hack Nerd Font

[font.bold]
family = "JetBrains Mono Nerd Font"

style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"
